name: Continout Deployment to VPS
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: | 
          cd /home/iqbal/facetro-be
          git reset --hard && git clean -df
          git pull origin master
          pm2 restart 1
          pm2 restart 5
