name: Continout Deployment to VPS
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: | 
          cd /home/xmod3905/facetro-be
          sudo npm install
          sudo git reset --hard && git clean -df
          sudo git pull origin master
